# Site settings
title: Rodrigo Castro
email: rodrigodesouzacastro@gmail.com
url: https://castrors.github.io/blog_old
description: "Androider and Mobile Tech Lover."
skills: "Desenvolvedor de aplicações mobile"
meta_author: Castro Rodrigo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 259b24 #80B3FF
  primary-rgb: "37,155,36" #"128,179,255"
  secondary: 212121 #FD6E8A
  secondary-dark: 111111 #A2122F

# Footer settings
footer:
  copyright: Castro Dev
  location: Localização
  social: Redes sociais
  credits: Créditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rodrigocastro_o
  - title: facebook
    url: https://www.facebook.com/boderodrigo
 # - title: stack-overflow
 #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: https://bitbucket.org/rodrigocastro
  - title: github
    url: http://github.com/castrors

# Postal address (add as many lines as necessary)
address:
  - line: São Paulo
  - line: SP - BR

# Credits content
credits:  'Esta página foi feita utilizando <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
